version: "3.9"

services:
  home:
    container_name: home
    build:
      context: ./deploy/app
    networks:
      - internal
    ports:
      - "54321:8001"
    depends_on:
      - user

  user:
    container_name: user
    build:
      context: ./deploy/user
    networks:
      - internal
    ports:
      - "31337"

networks:
  internal:
